version: 2
jobs:
  build:
    working_directory: ~/circleci-movilizer-webservice
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: circleci-movilizer-webservice-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-movilizer-webservice-{{ checksum "pom.xml" }}
      - run: mvn test

  package:
    working_directory: ~/circleci-movilizer-webservice
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/movilizer-webservice-15.11.2.0.jar

  deploy:
    working_directory: ~/circleci-movilizer-webservice
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: mvn -s settings.xml deploy

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/461ab315-3631-4075-b2b5-37146a0a4f01@96ece526-9c7d-48b0-8daf-8b93c90a5d18/CircleCI/bc3f3e1927744544b720483219d07eae/d1cadcd8-7e4e-4429-91a2-bd7ecb0f0b2a

workflows:
  version: 2
  test:
      jobs:
        - build
        - package:
            requires:
              - build

  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - package:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - package
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/